server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${mwh.datasource.driver-class-name}
    url: jdbc:mysql://${mwh.datasource.host}:${mwh.datasource.port}/${mwh.datasource.database}
    username: ${mwh.datasource.username}
    password: ${mwh.datasource.password}
  data:
    redis:
      host: ${mwh.redis.host}
      port: ${mwh.redis.port}
jwt:
  secret: ${mwh.jwt.secret}
  expiration: ${mwh.jwt.expiration}
dromara:
  x-file-storage:
    default-platform: ${mwh.minio.platform}
    minio:
      - platform: ${mwh.minio.platform}
        access-key: ${mwh.minio.access-key}
        secret-key: ${mwh.minio.secret-key}
        bucket-name: ${mwh.minio.bucket-name}
        end-point: ${mwh.minio.end-point}
        domain: ${mwh.minio.domain}
        enable-storage : ${mwh.minio.enable-storage}
        base-path: ${mwh.minio.base-path}